
version: 2.1

orbs:
 android: circleci/android@0.2.0

machine:
  environment:
      JAVA_HOME: /usr/lib/jvm/java-8-oracle
dependencies:
  pre:
    - sudo add-apt-repository -y ppa:webupd8team/java; sudo apt-get update
    - echo "oracle-java9-installer shared/accepted-oracle-license-v1-1 select true" | sudo debconf-set-selections
    - echo "oracle-java9-installer shared/accepted-oracle-license-v1-1 seen true" | sudo debconf-set-selections
    - sudo apt-get -y install oracle-java8-installer
    - sudo apt-get install oracle-java8-set-default
jobs:
  java-8:
    docker:
      - image: circleci/openjdk:8-jdk
  build:
    executor: android/android
    environment:
      FL_OUTPUT_DIR: ./app/build/outputs/apk/yapinternal/release/app-yapinternal-release.apk
      FASTLANE_LANE: upload_to_appcenter

    steps:
      - checkout
      - run:
          name: Install fastlane
          command: bundle install
      - run:
          name: Execute fastlane
          command: bundle exec fastlane $FASTLANE_LANE

workflows:
  build_and_test:
    jobs:
      - java-8:
      - build:
          filters:
            branches:
              only:
                - circle_ci
