
version: 2.1

orbs:
 android: circleci/android@0.2.0

machine:
  environment:
    ANDROID_HOME: /usr/local/android-sdk-linux
    JAVA6_HOME: /usr/lib/jvm/java-6-openjdk-amd64

  java:
    version: openjdk8

dependencies:
  override:
    - echo y | sudo apt-get update
    - echo y | sudo apt-get install libpango-1.0-0
    - echo y | sudo apt-get install openjdk-6-jre

    - echo y | android update sdk --no-ui --all --filter tools,platform-tools,build-tools-23.0.3,android-23,extra-google-m2repository,extra-google-google_play_services,extra-android-support
    - ANDROID_HOME=/usr/local/android-sdk-linux ./gradlew dependencies
jobs:
 build:
   executor: android/android
   environment:
     FL_OUTPUT_DIR: ./app/build/outputs/apk/yapinternal/release/app-yapinternal-release.apk
     FASTLANE_LANE: upload_to_appcenter

   steps:
     - checkout
     - run:
         name: Install fastlane
         command: bundle install
     - run:
        name: Execute fastlane
        command: bundle exec fastlane $FASTLANE_LANE

workflows:
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              only:
                - circle_ci
