
version: 2.1

orbs:
 android: circleci/android@0.2.0

jobs:
  build:
    executor: android/android
    environment:
      FL_OUTPUT_DIR: ./app/build/outputs/apk/yapinternal/release/app-yapinternal-release.apk
      FASTLANE_LANE: upload_to_appcenter
    steps:
      - checkout
      - run:
          name: Install Open JDK 8
          command: |
            sudo apt-get update
            sudo update-alternatives --set java /usr/lib/jvm/java-8-openjdk-amd64/bin/java
            sudo update-alternatives --set javac /usr/lib/jvm/java-8-openjdk-amd64/bin/javac
            java -version
      - run:
          name: Install fastlane
          command: bundle install
      - run:
          name: Execute fastlane
          command: bundle exec fastlane $FASTLANE_LANE

workflows:
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              only:
                - circle_ci
