package co.yap.yapcore.leanplum

data class UserAttributes(
    val accountType: String = "accountType",
    val email: String = "email",
    val nationality: String = "nationality",
    val firstName: String = "firstName",
    val lastName: String = "lastName",
    val documentsVerified: String = "documentsVerified",
    val mainUser: String = "mainUser",
    val householdUser: String = "householdUser",
    val youngUser: String = "youngUser",
    val b2bUser: String = "b2bUser",
    val country: String = "country",
    val city: String = "city",
    val uuid: String = "uuid",
    val customerId: String = "customerId",
    val signup_timestamp: String = "signup_timestamp",
    val signup_length: String = "signup_length",
    val biometric_login_enabled: String = "biometric_login_enabled",
    val eid_expired: String = "eid_expired",
    val account_active: String = "account_active",
    val eid_expiry_date: String = "eid_expiry_date",
    val Household_MainUser: Boolean = false,
    val signup_timestamp_Household_user: String = "signup_timestamp_Household_user",
    val account_active_HouseholdUser: Boolean = false,
    val account_active_HouseholdUser_timestamp: String = "account_active_HouseholdUser_timestamp",
    val account_active_HouseholdUser_monthly: Boolean = true,
    val account_cancel_HouseholdUser_timestamp: String = "account cancel HouseholdUser timestamp",
    val Household_account_expense_pots: String = "Household account expense pots",
    val Household_user_email_verified: Boolean = false,
    val Household_user_email: String = "Household_user_email",
    val Household_user_card_color: String = "Household_user_card_color",
    val phoneNumberVerifiedHHuser: Boolean = false
)