package co.yap.yapcore.enums

enum class AccountStatus {
    ON_BOARDED,
    MEETING_SCHEDULED,
    MEETING_SUCCESS,
    CAPTURED_EID,
    EID_EXPIRED,
    MEETING_FAILED,
    SOFT_KYC_DONE,
    SOFT_KYC_FAILED,
    PHYSICAL_CARD_ORDERED,
    CARD_ACTIVATED,
    PARNET_MOBILE_VERIFICATION_PENDING,
    PASS_CODE_PENDING,
    EMAIL_PENDING,
    INVITE_PENDING,
    INVITE_ACCEPTED,
    INVITE_DECLENIED
}