package co.yap.yapcore.enums

import androidx.annotation.Keep

@Keep
enum class AccountStatus {
    ON_BOARDED,
    MEETING_SCHEDULED,
    MEETING_SUCCESS,
    CAPTURED_EID,
    EID_EXPIRED,
    EID_UPDATED,
    EID_RESCAN_REQUIRE,
    REJECTED,
    MEETING_FAILED,
    SOFT_KYC_DONE,
    SOFT_KYC_FAILED,
    PHYSICAL_CARD_ORDERED,
    CARD_ACTIVATED,
    PARNET_MOBILE_VERIFICATION_PENDING,
    PASS_CODE_PENDING,
    EMAIL_PENDING,
    INVITE_PENDING,
    INVITE_ACCEPTED,
    INVITE_DECLINED,
    INVITATION_PENDING;

}