package co.yap.yapcore.enums

import androidx.annotation.Keep

@Keep
enum class PartnerBankStatus(val status: String) {
    SIGN_UP_PENDING("SIGN_UP_PENDING"),
    DOCUMENT_UPLOADED("DOCUMENT_UPLOADED"),
    PHYSICAL_CARD_PENDING("PHYSICAL_CARD_PENDING"),
    PHYSICAL_CARD_SUCCESS("PHYSICAL_CARD_SUCCESS"),
    HARD_KYC_PENDING("HARD_KYC_PENDING"),
    HARD_KYC_DONE("HARD_KYC_DONE"),
    APPROVED("APPROVED"),
    REJECTED("REJECTED"),
    ACTIVATED("ACTIVATED"),
    INITIAL_VERIFICATION_SUCCESSFUL("INITIAL_VERIFICATION_SUCCESSFUL"),
    REJECTED_AT_INITIAL_VERIFICATION("REJECTED_AT_INITIAL_VERIFICATION"),
    PROCESSED_SUCCESSFULLY("PROCESSED_SUCCESSFULLY")
}