package co.yap.yapcore.helpers

enum class ExtraKeys {
    TRANSACTION_OBJECT_STRING,
    TRANSACTION_OBJECT_CHILD_POSITION,
    TRANSACTION_OBJECT_GROUP_POSITION,
    SEND_MONEY_TYPE,
    IS_FROM_QR_CONTACT,
    Y2Y_BENEFICIARY_POSITION,
    IS_Y2Y_SEARCHING,
    TRANSACTION_RECEIPT,
    TRANSACTION_ID,
    TRANSACTION_RECEIPT_LIST,
    TAKE_IMAGE_FROM,
    IS_Y2Y_DATA,
    Y2Y_SELECTED_TAB_POS,
    IS_WAITING,
    BILL_PROVIDER,
    SELECTED_BILL_POSITION,
    SELECTED_BILL,
    IS_SKIP_PAY_BILL,
    IS_DELETED,
    IS_UPDATED
}