package co.yap.yapcore.helpers

enum class ExtraKeys {
    TRANSACTION_OBJECT_STRING,
    TRANSACTION_OBJECT_CHILD_POSITION,
    TRANSACTION_OBJECT_GROUP_POSITION,
    SEND_MONEY_TYPE,
    IS_FROM_QR_CONTACT,
    Y2Y_BENEFICIARY_POSITION,
    IS_Y2Y_SEARCHING,
    TRANSACTION_RECEIPT,
    TRANSACTION_ID,
    TRANSACTION_RECEIPT_LIST,
    TAKE_IMAGE_FROM
}